const colors = {
  black: {
    "--background": "#1a202c",
    "--btn-background": "#2be22e",
    "--shadow-background": "#2be22e",
    "--font-color": "goldenrod",
    "--font-color-card": "rgb(251, 192, 0)",
    "--card-back": "rgba(0, 0, 0, 0.15)",
    "--text-shadow-color": "black",
    "--fav-on": "red",
    "--fav-off": "black",
    "--btn-nav-back": "goldenrod",
    "--btn-nav-color": "black",
    "--nav-shadow": "black",
    "--result-back": "#00000007",
    "--input-back": "#00000038",
    "--filter": "invert(0) sepia(1) saturate(25) hue-rotate(500deg)",
  },
  violet: {
    "--background": "#4d1486",
    "--btn-background": "#dc2be2",
    "--shadow-background": "purple",
    "--font-color": "goldenrod",
    "--font-color-card": "rgb(251, 192, 0)",
    "--card-back": "rgba(0, 0, 0, 0.15)",
    "--text-shadow-color": "black",
    "--fav-on": "pink",
    "--fav-off": "black",
    "--btn-nav-back": "goldenrod",
    "--btn-nav-color": "black",
    "--nav-shadow": "black",
    "--result-back": "#00000007",
    "--input-back": "#00000038",
    "--filter": "invert(0) sepia(1) saturate(25) hue-rotate(300deg)",
  },
  white: {
    "--background": "#e8e4e4",
    "--btn-background": "#2ba6e2",
    "--shadow-background": "#2ba6e2",
    "--font-color": "#2071da",
    "--font-color-card": "rgb(0, 75, 251)",
    "--text-shadow-color": "blue",
    "--fav-on": "red",
    "--fav-off": "black",
    "--btn-nav-back": "#2083da",
    "--btn-nav-color": "black",
    "--nav-shadow": "black",
    "--result-back": "#00000007",
    "--input-back": "#00000038",
    "--filter": "invert(0) sepia(1) saturate(25) hue-rotate(200deg)",
    "--card-back": "rgba(0, 0, 0, 0.15)",
  },
};

export default colors;
